### ISSUE TITLE
1. app(default) is in Java

### ISSUE THREAD

**Issue by rpagyc** [Talentica/AndroidWithKotlin#8]
Hi! Thank you for these samples, however "1. app(default)" is written in Java ;)

**Comment by suyashgupta25** [comment]
Hi, Kotlin was introduced officially for android in Google IO 2017 few weeks back.
Since then we started exploring Kotlin and made samples out of it. But in Google IO, MVVM pattern was explained using Java. The same code we have included here as default app. 
The purpose was to let user know about MVVM pattern. 
Of course we will change it to Kotlin MVVM and update the master branch. Its WIP :)

**Comment by silwar** [comment]
Will PR be accepted for this issue/bug?
